### ISSUE TITLE
Using a custom gym

### ISSUE THREAD

**Issue by theSoenke** [rlgraph/rlgraph#63]
I have some issues registering a custom gym environment. Here is a code example:
```python
    from rlgraph.environments import OpenAIGymEnv

    env_id = "CustomEnv-v0"
    register(
        id=env_id,
        entry_point='custom_env:CustomEnv'
    )

    env = OpenAIGymEnv(gym_env=CustomEnv())

    agent = Agent.from_spec(
        agent_config,
        state_space=env.state_space,
        action_space=env.action_space
    )
    env_spec = {
        "type": "openai",
        "gym_env": env_id,
    }

    executor = ApexExecutor(
        environment_spec=env_spec,
        agent_config=agent_config,
    )
```

This causes the following error:
```
Starting workload, this will take some time for the agents to build.
Traceback (most recent call last):
  File "src/rlgraph/apex.py", line 120, in <module>
  File "src/rlgraph/apex.py", line 93, in main
    agent_config_path = os.path.join(os.getcwd(), FLAGS.output)
  File ".local/lib/python3.6/site-packages/rlgraph/execution/ray/ray_executor.py", line 178, in execute_workload
    worker_steps_executed, update_steps, discarded, queue_inserts = self._execute_step()
  File ".local/lib/python3.6/site-packages/rlgraph/execution/ray/apex/apex_executor.py", line 181, in _execute_step
    sample_batch_sizes = ray.get([task[1][1] for task in completed_sample_tasks])
  File ".local/lib/python3.6/site-packages/ray/worker.py", line 2307, in get
    raise value
ray.exceptions.RayTaskError: ray_RayValueWorker:execute_and_get_with_count() (pid=22290, host=desktop)
  File ".local/lib/python3.6/site-packages/gym/envs/registration.py", line 159, in spec
    return self.env_specs[id]
KeyError: 'CustomEnv-v0'

During handling of the above exception, another exception occurred:

ray_RayValueWorker:execute_and_get_with_count() (pid=22290, host=desktop)
  File ".local/lib/python3.6/site-packages/rlgraph/execution/ray/ray_value_worker.py", line 70, in __init__
    self.vector_env = SequentialVectorEnv(self.num_environments, env_spec, num_background_envs)
  File ".local/lib/python3.6/site-packages/rlgraph/environments/sequential_vector_env.py", line 38, in __init__
    super(SequentialVectorEnv, self).__init__(num_envs, env_spec)
  File ".local/lib/python3.6/site-packages/rlgraph/environments/vector_env.py", line 41, in __init__
    env = Environment.from_spec(env_spec)
  File ".local/lib/python3.6/site-packages/rlgraph/utils/specifiable.py", line 157, in from_spec
    specifiable_object = constructor(*ctor_args, **ctor_kwargs)
  File ".local/lib/python3.6/site-packages/rlgraph/environments/openai_gym.py", line 64, in __init__
    self.gym_env = gym.make(gym_env)  # Might raise gym.error.UnregisteredEnv or gym.error.DeprecatedEnv
  File ".local/lib/python3.6/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File ".local/lib/python3.6/site-packages/gym/envs/registration.py", line 124, in make
    spec = self.spec(path)
  File ".local/lib/python3.6/site-packages/gym/envs/registration.py", line 169, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: CustomEnv-v0
```

If I'm reading this right the gym env is not registered in the worker context. 

So currently I probably would have to add a custom environment directly to the `Environment.__lookup_classes__` in the rlgraph code right?

**Comment by michaelschaarschmidt** [comment]
Hi,

I just added functionality in Ray executors where you can now simply pass in a function that creates an environment, this should solve your issue:

```

    def test_from_callable_env_spec(self):
        env_spec = dict(
            type="openai",
            gym_env="CartPole-v0"
        )
        agent_config = config_from_path("configs/apex_agent_cartpole.json")

        def create_env():
            return Environment.from_spec(env_spec)

        # Pass lambda, not spec.
        executor = ApexExecutor(
            environment_spec=create_env,
            agent_config=agent_config,
        )

        # Define executor, test assembly.
        print("Successfully created executor.")

        # Executes actual workload.
        result = executor.execute_workload(workload=dict(num_timesteps=20000, report_interval=1000,
                                                         report_interval_min_seconds=1))
        print("Finished executing workload:")
print(result)
```

**Comment by michaelschaarschmidt** [comment]
Closing then, let me know if this does not work/reopen.

**Comment by theSoenke** [comment]
Thank you very much. Seems to work great
